# Generated by Django 3.1.2 on 2022-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=250)),
                ('EventCity', models.CharField(max_length=250)),
                ('EventCategory', models.CharField(choices=[('Family', 'Family'), ('18+', '18+'), ('Comedy Show', 'Comedy Show'), ('Children Show', 'Children Show')], max_length=250)),
                ('EventDate', models.DateField()),
                ('EventPrice', models.IntegerField()),
            ],
        ),
    ]
