# Generated by Django 3.1.2 on 2022-03-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='EventCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='EventCity',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='EventDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='EventName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='EventPrice',
            new_name='Price',
        ),
    ]
